# Generated by Django 5.2 on 2025-04-05 11:17

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Product',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=100)),
                ('slug', models.SlugField(blank=True, null=True)),
                ('image', models.ImageField(upload_to='img')),
                ('description', models.TextField(blank=True, null=True)),
                ('price', models.CharField(max_length=100)),
                ('category', models.CharField(blank=True, choices=[('Fictions', 'FICTIONS'), ('Nonfictions', 'NONFICTIONS')], max_length=15, null=True)),
            ],
        ),
    ]
